-- Enrichit la banque de propositions : +15 par catégorie (objectif 20 chacune).
-- Ton intime mais non explicite, aligné sur le DA "felted".

INSERT INTO challenge_suggestions (title, description, intensity) VALUES
-- Soft (+15)
('Réveil en douceur', 'Réveille-le/la demain avec un café au lit et rien d''autre au programme.', 'soft'),
('Le SMS de midi', 'Un message tendre qui le/la fera sourire en plein milieu de sa journée.', 'soft'),
('Slow improvisé', 'Une chanson, lumières baissées, on danse collés sans raison.', 'soft'),
('Photo souvenir', 'Reprenez ensemble la pose de votre toute première photo.', 'soft'),
('La liste secrète', 'Note trois choses que tu rêves de vivre avec elle/lui, puis échangez vos listes.', 'soft'),
('Bain moussant', 'Fais-lui couler un bain, bougies comprises, et laisse-le/la se détendre.', 'soft'),
('Petit-déjeuner surprise', 'Prépare son plat préféré sans prévenir et sers-le au lit.', 'soft'),
('Le regard appuyé', 'Au dîner, ne le/la quitte pas des yeux pendant tout un plat.', 'soft'),
('Mot sous l''oreiller', 'Glisse un billet doux qu''il/elle trouvera ce soir.', 'soft'),
('Promenade nocturne', 'Une balade main dans la main, sans téléphone, rien que vous deux.', 'soft'),
('Câlin d''une chanson', 'Un câlin qui dure un morceau entier, sans se lâcher.', 'soft'),
('Surprise dans sa journée', 'Fais-lui livrer un petit mot ou une douceur là où il/elle ne s''y attend pas.', 'soft'),
('La confidence', 'Raconte-lui un souvenir de vous deux qui te fait encore sourire.', 'soft'),
('Playlist pour deux', 'Crée la playlist de vos chansons et écoutez-la enlacés.', 'soft'),
('Le compliment précis', 'Avant de partir, dis-lui une chose précise que tu adores chez elle/lui.', 'soft'),
-- Hot (+15)
('Baiser dans le cou', 'Embrasse-le/la dans le cou par surprise… et arrête-toi là, pour l''instant.', 'hot'),
('Strip-tease musical', 'Une chanson, un vêtement de moins à chaque refrain.', 'hot'),
('Massage des épaules', 'Vingt minutes rien que pour son dos, huile tiède.', 'hot'),
('Devant le miroir', 'Habillez-vous l''un pour l''autre, face au miroir.', 'hot'),
('Dîner en tenue choisie', 'On dîne à la maison, dans la tenue choisie par l''autre.', 'hot'),
('Séance photo complice', 'Prends-le/la en photo comme tu le/la trouves désirable — gardées rien que pour vous.', 'hot'),
('Slow très proche', 'Une danse lente, collés, où les mains se baladent.', 'hot'),
('Le bandeau gourmand', 'Yeux bandés, devine les saveurs qu''il/elle te fait goûter.', 'hot'),
('Texto brûlant', 'Décris-lui par message ce que tu rêves de lui faire ce soir.', 'hot'),
('Film sans regarder l''écran', 'Tout un film à se câliner, sans jamais vraiment suivre l''histoire.', 'hot'),
('Réveil par des caresses', 'Réveille-le/la tout en douceur, en prenant ton temps.', 'hot'),
('Tu choisis ma tenue', 'L''autre décide ce que tu portes (ou pas) pour la soirée.', 'hot'),
('Confidence chuchotée', 'À l''oreille, avoue-lui une envie légère jamais formulée.', 'hot'),
('Le point sensible', 'Trouve l''endroit exact qui le/la fait frissonner.', 'hot'),
('Dessert interdit', 'Le dessert, c''est l''autre — on prend son temps.', 'hot'),
-- Hard (+15)
('Le maître du temps', 'Une heure où l''un décide de tout, en douceur. On inverse une autre fois.', 'hard'),
('Limites levées', 'Chacun nomme une chose à explorer ensemble, à votre rythme.', 'hard'),
('Deux inconnus', 'Jeu de rôle : ce soir, vous vous rencontrez pour la première fois.', 'hard'),
('Le compte à rebours', 'Interdit de se toucher avant la fin du minuteur. Tenez bon.', 'hard'),
('Chaud et froid', 'Yeux bandés, alterne la plume, le glaçon, la douceur.', 'hard'),
('Le mot de sécurité', 'Choisissez un mot, puis laissez-vous aller un cran plus loin.', 'hard'),
('Sous la table', 'Un dîner où l''un cherche à déstabiliser l''autre, l''air de rien.', 'hard'),
('Le scénario écrit', 'Écris une scène et faites-la jouer à deux ce soir.', 'hard'),
('Ce soir, j''ordonne', 'L''un guide, l''autre suit ; demain les rôles s''échangent.', 'hard'),
('Sans les mains', 'Interdit de se servir de ses mains pendant tout un moment.', 'hard'),
('L''audace partagée', 'Chacun propose une chose qu''il n''a jamais osé demander.', 'hard'),
('Cache-cache coquin', 'Un gage à la clé pour celui/celle qui trouve l''autre.', 'hard'),
('La nuit sans routine', 'Une nuit où l''on sort de ses habitudes, dans le respect des deux.', 'hard'),
('Strip-poker', 'Une partie de cartes, des enjeux… qui montent.', 'hard'),
('Ailleurs, un soir', 'Changez de décor : un lieu, une heure inhabituels, rien que pour vous.', 'hard');
