-- Traduction EN de la banque globale (les 60 entrées seed FR de 0008+0009).
-- Les anglophones obtiennent ainsi un vrai contenu (et non le repli FR).
INSERT INTO challenge_suggestions (title, description, intensity, locale) VALUES
-- Soft
('The forbidden word', 'A single text today, as suggestive as possible — without saying anything explicit.', 'soft', 'en'),
('Stolen compliment', 'Whisper in their ear, right now, what you love most about them.', 'soft', 'en'),
('A proper date', 'Like the first night: get ready, rediscover each other, no rushing.', 'soft', 'en'),
('Secret playlist', 'Pick three songs for an improvised slow dance tonight, in the living room.', 'soft', 'en'),
('The ten-second kiss', 'At the next goodbye, count to ten for real.', 'soft', 'en'),
('Massage with oils', 'One hour just for the other, dimmed lights, no phone.', 'hot', 'en'),
('Shower for two', 'Soap each other up, take your time.', 'hot', 'en'),
('Burning letter', 'Write down, in plain words, a desire you''ve never dared say out loud.', 'hot', 'en'),
('Dinner without cutlery', 'Feed each other, by hand, eyes locked.', 'hot', 'en'),
('Clumsy striptease', 'It doesn''t have to be perfect — just for you, just tonight.', 'hot', 'en'),
('Blindfold night', 'Blindfold on, you let yourself be guided all evening.', 'hard', 'en'),
('Tied hands', 'A scarf, and the other leads — ever so gently.', 'hard', 'en'),
('Imposed silence', 'One hour without a word: just gestures and glances.', 'hard', 'en'),
('Treasure hunt', 'Hide clues around the house leading to an… intimate surprise.', 'hard', 'en'),
('Roulette of desires', 'Each writes three wishes, draw one at random, honour the result.', 'hard', 'en'),
-- Soft (+15)
('Gentle wake-up', 'Wake them tomorrow with coffee in bed and nothing else on the agenda.', 'soft', 'en'),
('The noon text', 'A tender message that makes them smile in the middle of their day.', 'soft', 'en'),
('Improvised slow dance', 'One song, lights low, dance close for no reason.', 'soft', 'en'),
('Memory photo', 'Recreate together the pose of your very first photo.', 'soft', 'en'),
('The secret list', 'Write three things you dream of doing with them, then swap lists.', 'soft', 'en'),
('Bubble bath', 'Run them a bath, candles included, and let them unwind.', 'soft', 'en'),
('Surprise breakfast', 'Make their favourite dish unannounced and serve it in bed.', 'soft', 'en'),
('The lingering look', 'At dinner, don''t take your eyes off them for a whole course.', 'soft', 'en'),
('Note under the pillow', 'Slip a love note they''ll find tonight.', 'soft', 'en'),
('Night walk', 'A stroll hand in hand, no phone, just the two of you.', 'soft', 'en'),
('A song-long hug', 'A hug that lasts a whole track, without letting go.', 'soft', 'en'),
('Surprise in their day', 'Have a little note or treat delivered where they least expect it.', 'soft', 'en'),
('The confidence', 'Tell them a memory of the two of you that still makes you smile.', 'soft', 'en'),
('Playlist for two', 'Make the playlist of your songs and listen to it entwined.', 'soft', 'en'),
('The precise compliment', 'Before leaving, tell them one precise thing you adore about them.', 'soft', 'en'),
-- Hot (+15)
('Kiss on the neck', 'Kiss them on the neck by surprise… and stop there, for now.', 'hot', 'en'),
('Musical striptease', 'One song, one piece of clothing off with each chorus.', 'hot', 'en'),
('Shoulder massage', 'Twenty minutes just for their back, warm oil.', 'hot', 'en'),
('In front of the mirror', 'Dress (or undress) for each other, facing the mirror.', 'hot', 'en'),
('Dinner in chosen outfit', 'Dine at home, in the outfit the other picks.', 'hot', 'en'),
('Playful photo shoot', 'Photograph them the way you find them desirable — kept just for you.', 'hot', 'en'),
('Very close slow dance', 'A slow dance, pressed together, hands wandering.', 'hot', 'en'),
('The tasting blindfold', 'Blindfolded, guess the flavours they feed you.', 'hot', 'en'),
('Burning text', 'Describe by message what you''d love to do to them tonight.', 'hot', 'en'),
('A film, not the screen', 'A whole film spent cuddling, never really watching.', 'hot', 'en'),
('Woken by caresses', 'Wake them ever so gently, taking your time.', 'hot', 'en'),
('You pick my outfit', 'The other decides what you wear (or not) for the evening.', 'hot', 'en'),
('Whispered confession', 'In their ear, confess a light fantasy never spoken before.', 'hot', 'en'),
('The sensitive spot', 'Find the exact spot that makes them shiver.', 'hot', 'en'),
('Forbidden dessert', 'Dessert is the other — take your time.', 'hot', 'en'),
-- Hard (+15)
('Master of time', 'One hour where one decides everything, gently. Swap another time.', 'hard', 'en'),
('Limits lifted', 'Each names one thing to explore together, at your own pace.', 'hard', 'en'),
('Two strangers', 'Role-play: tonight, you meet for the first time.', 'hard', 'en'),
('The countdown', 'No touching before the timer ends. Hold on.', 'hard', 'en'),
('Hot and cold', 'Blindfolded, alternate the feather, the ice, the softness.', 'hard', 'en'),
('The safe word', 'Choose a word, then let yourselves go one notch further.', 'hard', 'en'),
('Under the table', 'A dinner where one tries to unsettle the other, ever so casually.', 'hard', 'en'),
('The written scene', 'Write a scene and act it out together tonight.', 'hard', 'en'),
('Tonight, I command', 'One leads, the other follows; tomorrow the roles swap.', 'hard', 'en'),
('No hands', 'No using your hands for a whole moment.', 'hard', 'en'),
('Shared boldness', 'Each proposes something they''ve never dared ask for.', 'hard', 'en'),
('Naughty hide-and-seek', 'A forfeit for whoever finds the other.', 'hard', 'en'),
('A night off the routine', 'A night where you step out of your habits, with mutual respect.', 'hard', 'en'),
('Strip poker', 'A card game, with stakes… that rise.', 'hard', 'en'),
('Elsewhere, one evening', 'Change the scenery: an unusual place and hour, just for you.', 'hard', 'en');
